//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativeVyatkaCore.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NativeVyatkaCore.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация не удалась. Проверьте логин или пароль.
        /// </summary>
        public static string Authorization_LoginFailed {
            get {
                return ResourceManager.GetString("Authorization_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось выполнить вход.
        /// </summary>
        public static string Authorization_SigninFailed {
            get {
                return ResourceManager.GetString("Authorization_SigninFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        public static string Dialog_Attention {
            get {
                return ResourceManager.GetString("Dialog_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить запись.
        /// </summary>
        public static string EditScreeen_DeleteFailed {
            get {
                return ResourceManager.GetString("EditScreeen_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись удалена.
        /// </summary>
        public static string EditScreeen_DeleteFinised {
            get {
                return ResourceManager.GetString("EditScreeen_DeleteFinised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить запись?.
        /// </summary>
        public static string EditScreeen_DeleteQuestion {
            get {
                return ResourceManager.GetString("EditScreeen_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить измения и сихранизировать запись?.
        /// </summary>
        public static string EditScreeen_SaveAndSync {
            get {
                return ResourceManager.GetString("EditScreeen_SaveAndSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхранизация не удалась.
        /// </summary>
        public static string EditScreeen_SyncFailed {
            get {
                return ResourceManager.GetString("EditScreeen_SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка открытия захоронения.
        /// </summary>
        public static string EditScreen_OpeningFailed {
            get {
                return ResourceManager.GetString("EditScreen_OpeningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись обновлена и синхранизирована.
        /// </summary>
        public static string EditScreen_SyncSuccess {
            get {
                return ResourceManager.GetString("EditScreen_SyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Камера не доступна.
        /// </summary>
        public static string MainScreeen_CameraNotAvailable {
            get {
                return ResourceManager.GetString("MainScreeen_CameraNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В настоящее время gps не доступен. Сделать запись невозможно.
        /// </summary>
        public static string MainScreeen_GpsNotAvailable {
            get {
                return ResourceManager.GetString("MainScreeen_GpsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхранизация записей с сервером не удалась.
        /// </summary>
        public static string MainScreeen_SyncFailed {
            get {
                return ResourceManager.GetString("MainScreeen_SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин не может быть пусты.
        /// </summary>
        public static string Validator_EmptyEmail {
            get {
                return ResourceManager.GetString("Validator_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть пусты.
        /// </summary>
        public static string Validator_EmptyPassword {
            get {
                return ResourceManager.GetString("Validator_EmptyPassword", resourceCulture);
            }
        }
    }
}
